version: '3.9'
services:
    web:
        build: .
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - persistent-data:/var/Danev_Persistent/
        #restart: always
volumes:
    persistent-data:
        driver: local